### ISSUE TITLE
[BUG] 设置修改后未能及时应用

### ISSUE THREAD

**Issue by xfl03** [Nsiso/NsisoLauncher#1]
# BUG内容
修改完设置并应用后，在启动器重启前不会使用新的设置。
# 复现流程
- 点击设置
- 修改任意设置（例如Java路径、JVM参数等容易从启动器日志中看出的设置）
- 点击应用，并关闭设置窗口
- 启动游戏，检查启动器日志

**Comment by Nsiso** [comment]
已优化部分实时实现
已增加对用户重启启动器的提示
