### ISSUE TITLE
能不能加一個修改UUID的功能？

### ISSUE THREAD

**Issue by FrankRx41** [Nsiso/NsisoLauncher#10]
每次重啟客戶端似乎會生成新的 UUID？
如果是，在 1.14.2 版本，統計信息保存在*saves/存檔名/%uuid%.json*中，所以不能保存遊戲統計信息。

**Comment by Nsiso** [comment]
若我没记错，离线验证时UUID的确为随机生成。正版用户不会发生这样的情况
感谢提醒，将在5个工作日内完善

**Comment by Nsiso** [comment]
通过重构和优化用户配置文件结构，已经修复问题
顺便引入了多用户保存与选择的新功能
修复代码已上传，但BUG和未完善的内容依然是很多的，不建议构建使用
