### ISSUE TITLE
你好，使用你们的启动器时，进度（成就）会丢失

### ISSUE THREAD

**Issue by FinaFina233** [Nsiso/NsisoLauncher#11]
进度卡在了之前完成的四个，之后的成就 例如 睡觉 获得了成就 关闭启动器与游戏 重新打开时又可以获得睡觉成就 令人头疼

**Comment by Nsiso** [comment]
已有人反馈该问题
原因是每次离线认证随机生成UUID，新UUID进入游戏将导致和上次进入游戏UUID不同从而读取不同成就配置文件
问题已经在代码中修复，您等待使用新版本即可，新版本即将发布（用户群中有体验版本）
原问题：https://github.com/Nsiso/NsisoLauncher/issues/10
