### ISSUE TITLE
无法使用openj9虚拟机通过统一通行证启动mc

### ISSUE THREAD

**Issue by ksgfk** [Nsiso/NsisoLauncher#12]
openj9版本:8.0.222.10
nsiso启动器版本:4.5.6819.2638
mc版本:1.12.2
forge版本:14.23.5.2838
具体表现是，点击启动游戏，进入启动中界面后直接跳回原始界面，具体看gif
~~我猜是不是启动参数的锅，mccl是可以启动的~~
![GIF.gif](https://i.loli.net/2019/08/04/uRWv3bfJQj7EUe9.gif)

**Comment by ksgfk** [comment]
好吧，刚刚试了一下离线、正版和通行证，只有统一通行证出现了这个问题

**Comment by Nsiso** [comment]
请检查你的验证核心是否位于包含中文的路径下，我估计你遇到的是这个问题：
openj9的javaagent对中文路径解码存在问题，任何只要使用了外置登录方案和openj9的启动器只要登录核心在中文路径下，均无法启动
这个是openj9的锅，我刚开始也不相信。。但是各种实验结果都指向这个原因
解决方案是：更换为Oracle Java而不是openjdk
我正在向openj9发起issue，希望他们能重视

**Comment by ksgfk** [comment]
还真是这个问题...真神奇

**Comment by Nsiso** [comment]
现在正在等待J9官方修复，这个issue可以关闭了
