### ISSUE TITLE
[Bug] 取消游戏启动，kill掉进程后的提示错误 (Version: 4.8.7168)

### ISSUE THREAD

**Issue by violetice** [Nsiso/NsisoLauncher#13]
![](https://ws1.sinaimg.cn/large/4273367bly1g7yt8pk9vjj20q20fggp9.jpg)

下载游戏资料，提示下载失败继续启动，点取消启动。
Version: 4.8.7168

**Comment by Nsiso** [comment]
收到反馈，因为近期学习繁重，修复速度可能比较慢，请耐心等候

**Comment by Nsiso** [comment]
DEV分支commit dc207a9中已修复
