### ISSUE TITLE
[Bug] 下载Forge成功，后续步骤报错 (Version: 4.8.7168)

### ISSUE THREAD

**Issue by violetice** [Nsiso/NsisoLauncher#14]
![](https://ws1.sinaimg.cn/large/4273367bly1g7yub07lexj20rs0fnq39.jpg)

![Image 5.png](https://ws1.sinaimg.cn/large/4273367bly1g7yucoc0tjj20k0056wei.jpg)
这个应该是下载成功的吧

**Comment by Nsiso** [comment]
请问安装的什么版本的forge？
如果是1.14的forge，报错是属于正常现象
因为forge官方为了阻止启动器自动安装进程（要恰饭），1.14的forge安装结构发生改变
我们会尽快修复和改进

**Comment by Nsiso** [comment]
该issue因长期未被发起者回复，无法进行后继跟踪。
如果有需要，请重新提交issue并附上更多信息
