### ISSUE TITLE
[功能请求]支持ZGC垃圾收集器

### ISSUE THREAD

**Issue by RealXuChe** [Nsiso/NsisoLauncher#15]
在 全局设置/高级参数设置/GC类型 下添加对ZGC的支持

**Comment by Nsiso** [comment]
我们打算将垃圾回收的选项变为自由填写（字符串输入）
我们将尽快实现此功能

**Comment by RealXuChe** [comment]
建议同时提供自由填写和选项选择两种模式，以满足对高级自定义和快速设置的需求。
说实话现在用复选框设置GC选项应该算是一个不错的功能。

**Comment by Nsiso** [comment]
DEV开发分支commit dc207a9中已改善此问题
改善后效果：
![8L75SKQ%R`VSLV1VN852QYU](https://user-images.githubusercontent.com/27906817/73563488-6517d580-4498-11ea-9fa7-3334f45057bc.png)
如有兴趣，可以自行构建体验此功能
