### ISSUE TITLE
[Bug]无法处理官方启动器未完成的下载

### ISSUE THREAD

**Issue by RealXuChe** [Nsiso/NsisoLauncher#16]
# 概述
无法处理官方启动器未完成的下载.

# 复现
1,使用官方启动器下载游戏并在下载完之前退出官方启动器.
2,打开nsiso,将游戏路径设为官方默认路径.
此时:
1,nsiso无法检测到未下载完成的版本.
2,在nsiso下载界面选择下载未下载完的游戏,nsiso直接提示下载完成,并不会进行下载.

# 预期
1,能够检测到未下载完成版本.
2,能够检测游戏文件损坏.

**Comment by Nsiso** [comment]
我觉得我可能不会把这个定义为bug而是定义为功能增强
检测到未下载的文件是有的，但是不会继承官启的下载，将来也不会支持，因为这是两个软件直接的问题了
检测游戏损坏是好主意，我尽量在下一个版本发布前修复
谢谢反馈

**Comment by Nsiso** [comment]
已经能检查游戏文件完整性，commit： 0a80d4aa1f38879837a116397bb6efd9436dc186
