### ISSUE TITLE
appveyor 配置个每次提交自动打包？

### ISSUE THREAD

**Issue by IOL0ol1** [Nsiso/NsisoLauncher#17]
控制台输出显示路径不匹配，Artifacts里面没东西，没配置好还是想自己手动Release故意设置的？

**Comment by Nsiso** [comment]
之前主要考虑的是CI的Deployments，忘了考虑有人对Build有下载需求，现在已经恢复设置，确认无误后请自行关闭comment

**Comment by Nsiso** [comment]
长时间未回复，我将关闭issue，遇到问题请重新commit
