### ISSUE TITLE
无法支持Fabric启动

### ISSUE THREAD

**Issue by Matrixchung** [Nsiso/NsisoLauncher#19]
如题
Fabric 1.15.2不支持

**Comment by Matrixchung** [comment]
启动器搜索不到 Fabric 的 Version 信息，目测是因为 JsonToVersion 方法内条件类似于 obj.ContainsKey("arguments") ，而 Fabric 的 JSON 多了一层 "patches" 所导致。

**Comment by Nsiso** [comment]
你好，感谢你的反馈
根据你的描述，Json最外层Patches是HMCL的json特征，系HMCL自动安装导致的。其擅自修改版本JSON文件，导致其他启动器无法正常启动游戏。根据HMCL官方回复，这么做的目的是为了更好的提供自动安装功能。
近期HMCL最新构建版本（非发布版本）听说已经解决了这个问题
我在这里并不建议你使用HMCL搭配其他启动器，推荐使用PCL等优秀启动器搭配Nsiso启动器食用

**Comment by Matrixchung** [comment]
> 你好，感谢你的反馈
> 根据你的描述，Json最外层Patches是HMCL的json特征，系HMCL自动安装导致的。其擅自修改版本JSON文件，导致其他启动器无法正常启动游戏。根据HMCL官方回复，这么做的目的是为了更好的提供自动安装功能。
> 近期HMCL最新构建版本（非发布版本）听说已经解决了这个问题
> 我在这里并不建议你使用HMCL搭配其他启动器，推荐使用PCL等优秀启动器搭配Nsiso启动器食用

好的，之前以为是 Fabric 的特性，我使用 Nsiso 启动器的目录确实由 HMCL 所创建。
感谢回复！
