### ISSUE TITLE
[BUG] "inheritsFrom"未能自动获取

### ISSUE THREAD

**Issue by xfl03** [Nsiso/NsisoLauncher#2]
# BUG内容
一个版本（json）如果声明了`inheritsFrom`，但是没有对应的json文件时，启动器不会自动获取这一json。
# 复现流程
- 建立`.minecraft/versions/test/test.json`，写入如下内容
```
{
    "id": "test",
    "inheritsFrom": "1.13",
    "jar": "1.13"
}
```
- 删除`.minecraft/versions/1.13/1.13.json`
- 查看版本选项，不存在test

**Comment by Nsiso** [comment]
此BUG已修复
