### ISSUE TITLE
功能建议：希望改进MultiThreadDownloader

### ISSUE THREAD

**Issue by Matrixchung** [Nsiso/NsisoLauncher#20]
您的 Dev 版本似乎采用了与 Master 不同的 HTTPDownload 函数，加入了异步处理的代码。但是当我调用此函数（无论是 Dev 还是 Master）下载大文件（100MB+ Zip格式 实际为客户端压缩包）时，DownloadWindow 内不显示进度，Visual Studio Debug 界面内显示占用内存逐渐上涨，由正常的 100MB 到 800MB+ 直至2G，同时任务管理器显示有网络读写，不过下载进度会被 Retry 机制打断。同时我观察到并没有任何的磁盘 I/O ，由此结合代码可以推测下载逻辑或许是全部以 Buffer 作为缓存，下载完后再进行 WriteAsync ？
这种方法面对下载版本 Assets 等小而多的文件确实没有问题，不过稍大一点（我测试的是 80MB+）的文件便会出现诸多问题。改用自己编写的函数调用 WebClient 进行下载则没有这个问题。

**Comment by Nsiso** [comment]
感谢反馈
Nsiso启动器下载依赖于File Stream，既HttpClient在Get后读取Response的Content stream，后写入文件stream。其中对内存buffer的分配只有1K（1024）
因为我也是刚转HttpClient不久，可能对该class不怎么熟悉，所以我需要对你说的情况进一步分析。请问是否可以发送一个下载URL进行测试？并且附上调试的更多信息，如内存占用时程序断点位置等，谢谢

**Comment by Matrixchung** [comment]
> 感谢反馈
> Nsiso启动器下载依赖于File Stream，既HttpClient在Get后读取Response的Content stream，后写入文件stream。其中对内存buffer的分配只有1K（1024）
> 因为我也是刚转HttpClient不久，可能对该class不怎么熟悉，所以我需要对你说的情况进一步分析。请问是否可以发送一个下载URL进行测试？并且附上调试的更多信息，如内存占用时程序断点位置等，谢谢

Buffer 的大小和 Worker 的线程数我都试着去调整过，但是看来是逻辑本身的问题，调整 Buffer 并没有什么作用。
URL 的话，我这边是 Fork 下来之后新写了一个 UpdateWindow 用于服务器客户端的自动更新 = = 
所以抱歉无法提供 URL （其实随便一个大过80`100M+的文件都可以测试）
断点的话因为我已经重写了 MultiThreadDownloader ，大致是使用 WebClient.DownloadFileAsync 并加上传递事件委托用以配合 UpdateWindow 的 ProgressBar ，因而目前不好提供断点了。

**Comment by Nsiso** [comment]
该Issue需要等待人工复审和进一步追加信息，暂时挂起

**Comment by Nsiso** [comment]
你好，通过我朋友辅助调试得知，该BUG属实，会在大文件下载时出现问题。
他使用第三方大学镜像站下载系统ISO文件，超过了4GB，的确下载时会报错无法写入缓存
经过查阅文档，貌似是由于HttpClient定义模式选择不恰当引起的。
因为我现在无法直接对代码进行更改（学业繁忙），邀请您进行测试
将using (var getResult = await NetRequester.Client.GetAsync(task.From, cancelToken))
改为
using (var getResult = await NetRequester.Client.GetAsync(task.From, HttpCompletionOption.ResponseHeadersRead, cancelToken))
既添加指定Option HttpCompletionOption.ResponseHeadersRead
如果修复成功，请关闭issue，若问题还存在，请继续跟踪

**Comment by Matrixchung** [comment]
您好，按你的方法修改后解决了问题。我很荣幸能为这个项目的发展尽一份力，谢谢！

**Comment by Nsiso** [comment]
谢谢反馈😘❤
