### ISSUE TITLE
找不到启动版本

### ISSUE THREAD

**Issue by ddaodan** [Nsiso/NsisoLauncher#22]
**Describe the bug**
打开启动器，启动版本里是空的，但是version文件夹里是有游戏版本的

**Screenshots**
![image](https://user-images.githubusercontent.com/40017293/80676740-050deb00-8aea-11ea-9be9-973efd5ab8ad.png)
![image](https://user-images.githubusercontent.com/40017293/80676781-1525ca80-8aea-11ea-9cd0-5f0f5c707daa.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [4.8.7368.23222]

**Additional context**
这个版本是用HMCL下载安装的，是原版+Forge的
推测是启动器不支持这种方式的版本

**Comment by Nsiso** [comment]
你好
如果有能力请复制粘贴一份版本文件夹内的引导Json文件（版本Json）
如果没意外的话，可能是因为HMCL擅自修改了引导Json的结构
HMCL在安装扩展时会非正常修改Json文件，据HMCL声明为：“维持HMCL正常安装扩展必要途径”
HMCL修改Json后除了HMCL可以启动该版本外，其他启动器均无法启动，包括官方启动器
--据说HMCL新版本已修复？
因此我不建议你使用HMCL启动器，如果你是nsiso启动器和HMCL启动器搭配使用，请自行进行取舍。
具体分析还是要看你贴出来的json，没意外就是我上面说的

**Comment by ddaodan** [comment]
> 你好
> 如果有能力请复制粘贴一份版本文件夹内的引导json文件(版本json)
> 如果没意外的话，可能是因为hmcl擅自修改了引导json的结构
> hmcl在安装扩展时会非正常修改json文件，据hmcl声明为：“维持hmcl正常安装扩展必要途径”
> hmcl修改json后除了hmcl可以启动该版本外，其他启动器均无法启动，包括官方启动器
> -据说hmcl新版本已修复？
> 因此我不建议你使用hmcl启动器，如果你是nsiso启动器和hmcl启动器搭配使用，请自行进行取舍.
> 具体分析还是要看你贴出来的json，没意外就是我上面说的


hmcl.json
[hmcl.txt](https://github.com/Nsiso/NsisoLauncher/files/4569748/hmcl.txt)

**Comment by vungsung** [comment]
@ddaodan
- `版本.json`指的是launcher_profiles.json, 这default.txt貌似是各版本依赖的资源配置文件
- Nsiso不会读hmcl.json，而是读launcher_profiles.json；而且你的hmcl.json里的路径是指向%Appdata%目录，但你截图中的游戏目录是在当前目录下的。不过不必花时间处理hmcl.json了，应该是`launcher_profiles.json`的锅才对，看能不能贴上来

**Comment by ddaodan** [comment]
> @ddaodan
> 
> * `版本.json`指的是launcher_profiles.json, 这default.txt貌似是各版本依赖的资源配置文件
> * Nsiso不会读hmcl.json，而是读launcher_profiles.json；而且你的hmcl.json里的路径是指向%Appdata%目录，但你截图中的游戏目录是在当前目录下的。不过不必花时间处理hmcl.json了，应该是`launcher_profiles.json`的锅才对，看能不能贴上来

launcher_profiles.json
`{"selectedProfile": "(Default)","profiles": {"(Default)": {"name": "(Default)"}},"clientToken": "88888888-8888-8888-8888-888888888888"}`
对比了一下，跟Nsiso生成的是一样的

**Comment by vungsung** [comment]
Nsiso应该只看目录不看配置 ([#L367](
https://github.com/Nsiso/NsisoLauncher/blob/55c5376085d0eccd5da7b031db10965df727bf78/src/NsisoLauncherCore/VersionReader.cs#L367))
如果启动器没配置错, 却连一个版本也找不到真就bug+=1
![配置](https://i.imgur.com/1t5jUap.png)

**Comment by Nsiso** [comment]
> > 你好
> > 如果有能力请复制粘贴一份版本文件夹内的引导json文件(版本json)
> > 如果没意外的话，可能是因为hmcl擅自修改了引导json的结构
> > hmcl在安装扩展时会非正常修改json文件，据hmcl声明为：“维持hmcl正常安装扩展必要途径”
> > hmcl修改json后除了hmcl可以启动该版本外，其他启动器均无法启动，包括官方启动器
> > -据说hmcl新版本已修复？
> > 因此我不建议你使用hmcl启动器，如果你是nsiso启动器和hmcl启动器搭配使用，请自行进行取舍.
> > 具体分析还是要看你贴出来的json，没意外就是我上面说的
> 
> [hmcl.json](https://github.com/Nsiso/NsisoLauncher/files/4569748/hmcl.txt)
> [版本json](https://github.com/Nsiso/NsisoLauncher/files/4569752/default.txt)

版本json我看了下
是HMCL篡改json的问题无误（特征：patches，root等）。
即因为：hmcl在安装扩展时会非正常修改json文件，修改后json除了hmcl可以启动该版本外，其他启动器均无法启动（基本全部主流启动器，部分启动器会强制转换），包括官方启动器
解决方案：
不要使用HMCL安装游戏或扩展，拿来启动可以，但是不要装，用其他启动器装或者手动装
或者尝试使用新版本hmcl（听说新版本修复了这个问题）

综上所述，这个问题不属于bug，也不会进行修复和改善
虽然这个问题很多人反馈了，但还是感谢你的反馈

**Comment by Nsiso** [comment]
关联issue：#19
