### ISSUE TITLE
某些皮肤站同账号多ID登录时选择ID功能的缺失

### ISSUE THREAD

**Issue by ZYLHL** [Nsiso/NsisoLauncher#24]
多数皮肤站支持同一个账号创建不同名称的角色，
Nsiso启动器还没能支持从多个角色中任选其一启动的功能，如果遇到用皮肤站外置
登录正巧该皮肤站账号添加了多个id不同的角色，Nsiso将没法顺利启动游戏。

**Comment by Nsiso** [comment]
已提交修复，dev分支 commit：3b1e3b7
