### ISSUE TITLE
添加外置登录选择角色

### ISSUE THREAD

**Issue by MicroDeveci** [Nsiso/NsisoLauncher#26]
![QQ图片20200717181650](https://user-images.githubusercontent.com/66165361/87776074-be629e00-c859-11ea-9ae1-981323a79e09.png)
皮肤站有几个角色的用户，不能登录。启动器又不能选择角色，皮肤站又不能改默认。

**Comment by Nsiso** [comment]
关联 #24

**Comment by Nsiso** [comment]
已提交修复，dev分支 commit：3b1e3b7
