### ISSUE TITLE
authlie-injector 返回ID不存在

### ISSUE THREAD

**Issue by nicklly** [Nsiso/NsisoLauncher#29]
![37}L%__OJPO5R0D {)@6RTK](https://user-images.githubusercontent.com/17716585/88043695-5d500880-cb80-11ea-95d4-8bbf0b7eab5c.png)
![R9ZG% _$ D`F~Z7F}W4D($R](https://user-images.githubusercontent.com/17716585/88043705-5de89f00-cb80-11ea-96d5-0a4f9643adc9.png)

authlie-injector登陆 添加了Yggdrasil API 认证服务 使用游戏ID登陆 会提示ID不存在 其他启动器测试均正常

**Comment by Nsiso** [comment]
在新版本中（dev分支）已完善
