### ISSUE TITLE
建议:关于显示服务器信息

### ISSUE THREAD

**Issue by Shuazijun** [Nsiso/NsisoLauncher#3]
如题,现在主界面只能单独显示一个服务器的连接信息,希望添加更多的设置插槽,毕竟有很多服务器是多条线路的

**Comment by Icetebe** [comment]
服务器是多条线路的，这些线路都是通向一个服务器，自然Motd内容也一样，唯一不同的就是显示延迟，没太大意义呀

**Comment by Nsiso** [comment]
经过几个月的调查和报告，我们发现“多路服务器信息显示”功能价值较低，并且开发成本比较高，我们将放弃这个功能的增强，我们表示抱歉。
但后期的高版本我们会增强用户自定义插件功能，也许可能会做到这种类似功能的插件
