### ISSUE TITLE
无法启动1.8.9

### ISSUE THREAD

**Issue by 313266** [Nsiso/NsisoLauncher#32]
我用nsiso下载版本总是下载失败，用hmcl下载了1.8.9，nsiso打不开，1.13.2以上我能打开

**Comment by Nsiso** [comment]
能提供下相关文件吗

**Comment by mahoshojoHCG** [comment]
hmcl下载的东西和别的启动器不兼容

**Comment by Nsiso** [comment]
长时间未回复，猜测是hmcl修改版本引导json导致
若有跟进，请重新开一个issue
