### ISSUE TITLE
改善对 authlib-injector 的支持

### ISSUE THREAD

**Issue by yushijinhun** [Nsiso/NsisoLauncher#4]
1. 目前配置 authlib-injector 需要手动下载 authlib-injector.jar，并且还需要手动设置启动参数。但实际上这些都可以由启动器自动完成，服主只需要输入 URL。
2. 统一通行证的 nide8auth.jar 可以用 authlib-injector.jar 替代。并且这样的话，两者可以使用同一个验证逻辑。

**Comment by Nsiso** [comment]
已完成改善
