### ISSUE TITLE
错误日志

### ISSUE THREAD

**Issue by 2276861278** [Nsiso/NsisoLauncher#40]
========NsisoLauncher Error Report========
Date:2021/1/15 10:44:43    Launcher Version:4.8.7368.23222
Exception Detail:
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 NsisoLauncher.MainWindow.<LaunchGameFromArgs>d__6.MoveNext()

**Comment by Nsiso** [comment]
能具体说是怎样触发的吗
尝试删除配置文件能解决这个问题吗

**Comment by Nsiso** [comment]
长时间未回复，若要进行跟踪请重新开启一个issue
