### ISSUE TITLE
启动器错误

### ISSUE THREAD

**Issue by 264388324** [Nsiso/NsisoLauncher#41]
========NsisoLauncher Error Report========
Date:2021/1/29 10:05:31    Launcher Version:4.8.7368.23222
Exception Detail:
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 NsisoLauncher.Config.ConfigHandler.Read()
   在 NsisoLauncher.Config.ConfigHandler..ctor()
   在 NsisoLauncher.App.InitializeApplication(StartupEventArgs e)
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by 264388324** [comment]
删除配置文件就正常了

**Comment by Nsiso** [comment]
可以试一下dev分支中的开发版本 看看还会出现这样的问题吗

**Comment by Nsiso** [comment]
问题未及时跟进，故关闭
若有新问题可以重新提交issue
