### ISSUE TITLE
dev

### ISSUE THREAD

**Issue by 264388324** [Nsiso/NsisoLauncher#45]
========NsisoLauncher Error Report========
Date:2021/2/9 12:09:28    Launcher Version:4.10.7710.20254
Exception Detail:
System.InvalidOperationException: 集合 Remove 事件必须指定项位置。
   在 MS.Internal.Data.EnumerableCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   在 System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   在 NsisoLauncherCore.Util.ObservableDictionary`2.RemoveWithNotification(TKey key)
   在 NsisoLauncher.Views.Controls.AuthModuleControl.<DelButton_Click>d__11.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by 264388324** [comment]
还有使用统一登录验证时要用哪个登录

**Comment by 264388324** [comment]
========NsisoLauncher Error Report========
Date:2021/2/9 12:12:55    Launcher Version:4.10.7710.20254
Exception Detail:
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.get_Item(Int32 index)
   在 MS.Internal.Data.EnumerableCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   在 System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   在 NsisoLauncherCore.Util.ObservableDictionary`2.UpdateWithNotification(TKey key, TValue value)
   在 NsisoLauncher.ViewModels.Pages.UserPageViewModel.Login(UserNode user)
   在 NsisoLauncher.ViewModels.Pages.UserPageViewModel.<OfflineLogin>d__59.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 NsisoLauncher.ViewModels.Pages.UserPageViewModel.<<-ctor>b__57_0>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by 264388324** [comment]
========NsisoLauncher Error Report========
Date:2021/2/9 12:13:43    Launcher Version:4.10.7710.20254
Exception Detail:
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 NsisoLauncherCore.Net.Nide8API.APIHandler.<GetInfoAsync>d__7.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 NsisoLauncher.ViewModels.Pages.LaunchPageViewModel.<LaunchFromVM>d__56.MoveNext()

**Comment by 264388324** [comment]
是我的问题还是启动器问题

**Comment by Nsiso** [comment]
怎么触发的呢

**Comment by 264388324** [comment]
账户离线登录随便名字，然后注销再输入一遍同样的名字

**Comment by 264388324** [comment]
添加用户验证，添加完后选择添加的用户验证，再选其他（正版/离线）验证点删除

**Comment by 264388324** [comment]
还有一个是启动游戏时出错，忘了怎么触发的了

**Comment by 264388324** [comment]
========NsisoLauncher Error Report========
Date:2021/2/15 17:14:00    Launcher Version:4.10.7716.30504
Exception Detail:
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 NsisoLauncher.ViewModels.Pages.WelcomePageViewModel.<RefreshUser>d__26.MoveNext() 位置 F:\dev\NsisoLauncher-dev\src\NsisoLauncher\ViewModels\Pages\WelcomePageViewModel.cs:行号 0
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 NsisoLauncher.ViewModels.Pages.WelcomePageViewModel.<CheckEnvironment>d__24.MoveNext() 位置 F:\dev\NsisoLauncher-dev\src\NsisoLauncher\ViewModels\Pages\WelcomePageViewModel.cs:行号 118
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 NsisoLauncher.ViewModels.Pages.WelcomePageViewModel.<<-ctor>b__20_0>d.MoveNext() 位置 F:\dev\NsisoLauncher-dev\src\NsisoLauncher\ViewModels\Pages\WelcomePageViewModel.cs:行号 61
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by 264388324** [comment]
当有账户时把正版和离线验证都删掉后启动启动器

**Comment by Nsiso** [comment]
你好
我已经检查过，您使用的是 NsisoLauncher.Views.Controls.AuthModuleControl 控件对验证模型进行操作的
因为我个人失误 这个控件我没有删除，在4.10版本中，这种验证方式被取消，我将尽快进行匹配
建议不要在生产环境中使用 4.10，该版本还未完全开发完成，bug是比较多的
我将尽快修复这些bug

**Comment by Nsiso** [comment]
修复完成 4.10已完善验证模型，请检查是否问题解决
若有问题请重新open issue
