### ISSUE TITLE
在打开下载器的时候可以直接刷新而不是手动刷新？

### ISSUE THREAD

**Issue by Wenz-jam** [Nsiso/NsisoLauncher#46]
**Is your feature request related to a problem? Please describe.**
在4.9版本中发现版本获取需要手动点击刷新。
**Describe the solution you'd like**
希望在首次打开后自动跟新列表，刷新用作跟新失败后。
**Describe alternatives you've considered**
在src\NsisoLauncher\Views\Windows\NewDownloadTaskWindow.xaml.cs的NewDownloadTaskWindow()函数中加入refreshversion()函数以解决之
**Additional context**
![捕获](https://user-images.githubusercontent.com/81887980/120771724-1f6a9180-c552-11eb-9730-fd4131a77d4a.PNG)
这看着有点像启动器坏了，让人心里膈应

**Comment by Nsiso** [comment]
确实，将会进行优化
