### ISSUE TITLE
提示游戏非正常退出

### ISSUE THREAD

**Issue by gqm36524** [Nsiso/NsisoLauncher#47]
客户端1.12.2，移除全部mod依然提示这个。用其他启动器就可以正常运行。这啥情况

**Comment by gqm36524** [comment]
我试了一下旧版4.5也是这个问题，但是那边有报错。就是下图
![image](https://user-images.githubusercontent.com/21172441/121310931-7a2b3100-c936-11eb-8672-da7f0739f049.png)

**Comment by gqm36524** [comment]
找到原因了，只要客户端安装了OptiFine这个启动器就无法正常启动游戏了。希望作者解决一下

**Comment by Nsiso** [comment]
能上传一个sample看看吗

**Comment by gqm36524** [comment]
我用mods方式加载OptiFine就没事啦，已经解决了。这款启动器应该算是目前支持统一通行证里最优质的了，但是我感觉使用引导设计的没有4.5那个版本更流程化，让人有点搞不懂

**Comment by Nsiso** [comment]
不使用mods闪退的样品有吗

**Comment by gqm36524** [comment]
用HMCL启动器，安装一个1.12.2版本带Forige+OptiFine的就行。然后用这个启动器启动就会遇到。
