### ISSUE TITLE
出错，下载出错，三个下载源全部尝试过了

### ISSUE THREAD

**Issue by Noka1998** [Nsiso/NsisoLauncher#49]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Nsiso** [comment]
没有贴详细信息
请提供一下日志文件

**Comment by Nsiso** [comment]
长时间未回复 关闭issue，如果有需要请重新开一个issue
