### ISSUE TITLE
大佬年过了记得修复BUG发布新版本我帮你整理下

### ISSUE THREAD

**Issue by Icetebe** [Nsiso/NsisoLauncher#5]
①修复自定义游戏标题的功能 ②修复开启强制统一模式后就无法显示服务器状态和无法直接进入服务器的问题 ③最好能根据游戏API实时头像 ④最好能支持中文统一通行证账号登陆 ⑤启动器音乐关闭时的图标有斜杠的优化 ⑥统一通行证只要记住账号密码，下次登陆就算换了账号输入了正确密码也还是上次记住的账号，除非重置用户信息的BUG

**Comment by Nsiso** [comment]
中文统一通行证账号登陆已修复

**Comment by Nsiso** [comment]
1.复自定义游戏标题 没有问题，启动后需保持启动器为打开状况或不与mod冲突
2.修复开启强制统一模式后就无法显示服务器状态和无法直接进入服务器的问题 这个可以的啊
3.最好能根据游戏API实时头像 已优化，正版用户显示皮肤头像
4.最好能支持中文统一通行证账号登陆 已优化
5.统一通行证只要记住账号密码，下次登陆就算换了账号输入了正确密码也还是上次记住的账号，除非重置用户信息的BUG 已优化
