### ISSUE TITLE
启动器读取文件出错

### ISSUE THREAD

**Issue by Wenz-jam** [Nsiso/NsisoLauncher#51]
版本是action里的忘记了4.10.x
不是系统就是messagebox提示的文件读取出错，之后启动器就报错了，或者直接打不开来
首先启动器目录下没有中文字符，可以排除路径问题
其次的话也是把config.js删了就好了，怕不是一样的俩问题

**Comment by Nsiso** [comment]
。。。为什么我听不懂你在说啥
“版本是action里的忘记了4.10.x”这句话是啥意思
然后“不是系统就是messagebox提示的文件读取出错”系统提示的话也是messagebox的
“怕不是一样的俩问题”是哪两个问题

**Comment by Nsiso** [comment]
长时间未回复 关闭该issue 若还遇到该问题请重新提交新的issue
