### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by ravizhan** [Nsiso/NsisoLauncher#7]
请问如何解决？
邮箱：ravizhan@hotmail.com

**Comment by Nsiso** [comment]
siso启动器的启动核心目前单独分离开源。
Nsiso启动器通过核心开源<->应用开源的分离结构，以便稳定更新。同时封装后的启动核心会更方便其他人使用Nsiso启动核心。未来有空我将会发布至Mcbbs对外开放并发布开发视频教程。
启动核心Github源：https://github.com/Nsiso/NsisoLauncherCore

**Comment by Nsiso** [comment]
你导入nsiso launcher core就可以了
