### ISSUE TITLE
authlib-injector无法加载

### ISSUE THREAD

**Issue by BecodReyes** [Nsiso/NsisoLauncher#8]
authlib-injector无法加载
已试过绝对路径和相对路径
![17-53-33](https://user-images.githubusercontent.com/35525491/57177344-afcad980-6e95-11e9-81cd-555b2b8fab43.png)

**Comment by xiaonian233** [comment]
老哥试试别的启动器？我认为：Error opening zip file or JAR manifest missing这个错误不像是启动器的锅
你试试java -javagent:你的jar这个在cmd里面看看是不是相同提示

**Comment by BecodReyes** [comment]
试过MCCL是可以用这个authlib-injector启动的
![image](https://user-images.githubusercontent.com/35525491/57526463-0f2a5d00-7360-11e9-8ebd-365d1252cb04.png)

倒是NsisoLauncher启动不了
![image](https://user-images.githubusercontent.com/35525491/57526376-d68a8380-735f-11e9-9612-d67082de978a.png)

**Comment by BecodReyes** [comment]
参照统一启动的javaagent的设置以及启动log之后得出了：
启动器上的JavaAgent参数框内不需要加-javaagent:这个参数
![image](https://user-images.githubusercontent.com/35525491/57527573-9a0c5700-7362-11e9-8d7e-e4347302e5d4.png)

**Comment by Nsiso** [comment]
是的。。。不需要再加-javaagent:这个参数了。。我新版本会加上提示谢谢提醒
