### ISSUE TITLE
寒冰之刄提供：客户端防盗原理

### ISSUE THREAD

**Issue by Icetebe** [Nsiso/NsisoLauncher#9]
防客户端盗初期想法，在模组核心jar文件都按压缩包加上密码，这样mc是启动不了的，但在启动器里引导mc时使用里面预设密码解密加载，启动器（安全性加壳）无法反编辑，你也看不到里面的预设密码，从而实现无伤99%免破解。

**Comment by Nsiso** [comment]
无法实现
